name: sports_predict_env
channels:
  - defaults
dependencies:
  - _tflow_190_select=0.0.1=gpu
  - absl-py=0.6.1=py36_0
  - appdirs=1.4.3=py36h28b3542_0
  - asn1crypto=0.24.0=py36_0
  - astor=0.7.1=py36_0
  - attrs=18.2.0=py36h28b3542_0
  - automat=0.7.0=py36_0
  - backcall=0.1.0=py36_0
  - beautifulsoup4=4.7.1=py36_1
  - blas=1.0=mkl
  - bleach=3.0.2=py36_0
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py36_0
  - cffi=1.11.5=py36h74b6da3_1
  - colorama=0.4.0=py36_0
  - constantly=15.1.0=py36h28b3542_0
  - cryptography=2.5=py36h7a1dbc1_0
  - cudatoolkit=9.0=1
  - cudnn=7.1.4=cuda9.0_0
  - cycler=0.10.0=py36h009560c_0
  - cython=0.29=py36ha925a31_0
  - decorator=4.3.0=py36_0
  - entrypoints=0.2.3=py36_2
  - freetype=2.9.1=ha9979f8_1
  - gast=0.2.0=py36_0
  - grpcio=1.12.1=py36h1a1b453_0
  - h5py=2.8.0=py36h3bdd7fb_2
  - hdf5=1.10.2=hac2f561_1
  - html5lib=1.0.1=py36_0
  - hyperlink=18.0.0=py36_0
  - icc_rt=2017.0.4=h97af966_0
  - icu=58.2=ha66f8fd_1
  - idna=2.7=py36_0
  - incremental=17.5.0=py36_0
  - intel-openmp=2019.0=118
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.1.1=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - ipywidgets=7.4.2=py36_0
  - jedi=0.13.1=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=2.6.0=py36h7636477_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.4.0=py36_0
  - jupyterlab=0.35.3=py36_0
  - jupyterlab_server=0.2.0=py36_0
  - keras=2.2.2=0
  - keras-applications=1.0.4=py36_1
  - keras-base=2.2.2=py36_0
  - keras-gpu=2.2.2=0
  - keras-preprocessing=1.0.2=py36_1
  - kiwisolver=1.0.1=py36h6538335_0
  - libiconv=1.15=h1df5818_7
  - libpng=1.6.35=h2a8f88b_0
  - libprotobuf=3.6.0=h1a1b453_0
  - libsodium=1.0.16=h9d3ae62_0
  - libxml2=2.9.9=h464c3ec_0
  - libxslt=1.1.33=h579f668_0
  - lxml=4.3.1=py36h1350720_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.0.1=py36_0
  - markupsafe=1.0=py36hfa6e2cd_1
  - matplotlib=3.0.1=py36hc8f65d3_0
  - mistune=0.8.4=py36he774522_0
  - mkl=2019.0=118
  - mkl_fft=1.0.6=py36hdbbee80_0
  - mkl_random=1.0.1=py36h77b88f5_1
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36h3a5bc1b_0
  - notebook=5.7.0=py36_0
  - numpy=1.15.3=py36ha559c80_0
  - numpy-base=1.15.3=py36h8128ebf_0
  - openssl=1.1.1a=he774522_0
  - pandas=0.23.4=py36h830ac7b_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.1=py36_0
  - pickleshare=0.7.5=py36_0
  - prometheus_client=0.4.2=py36_0
  - prompt_toolkit=2.0.7=py36_0
  - protobuf=3.6.0=py36he025d50_0
  - pyasn1=0.4.4=py36h28b3542_0
  - pyasn1-modules=0.2.2=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.2.0=py36hb010967_0
  - pyhamcrest=1.9.0=py36_2
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.2=py36_0
  - pyqt=5.9.2=py36h6538335_2
  - pysocks=1.6.8=py36_0
  - python=3.6.7=h33f27b4_1
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pywin32=223=py36hfa6e2cd_1
  - pywinpty=0.5.4=py36_0
  - pyyaml=3.13=py36hfa6e2cd_0
  - pyzmq=17.1.2=py36hfa6e2cd_0
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=4.4.2=py36_0
  - scipy=1.1.0=py36h4f6bf74_1
  - selenium=3.14.1=py36he774522_0
  - send2trash=1.5.0=py36_0
  - service_identity=17.0.0=py36h28b3542_0
  - setuptools=39.1.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36h6538335_0
  - six=1.11.0=py36_1
  - soupsieve=1.7.1=py36_0
  - sqlite=3.26.0=he774522_0
  - tensorboard=1.9.0=py36he025d50_0
  - tensorflow=1.9.0=gpu_py36hfdee9c2_1
  - tensorflow-base=1.9.0=gpu_py36h6e53903_0
  - tensorflow-gpu=1.9.0=hf154084_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.1=py36_1
  - testpath=0.4.2=py36_0
  - tornado=5.1.1=py36hfa6e2cd_0
  - traitlets=4.3.2=py36h096827d_0
  - twisted=18.9.0=py36he774522_0
  - urllib3=1.24=py36_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_0
  - wcwidth=0.1.7=py36h3d5aa90_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.14.1=py36_0
  - wheel=0.32.2=py36_0
  - widgetsnbextension=3.4.2=py36_0
  - win_inet_pton=1.0.1=py36_1
  - win_unicode_console=0.5=py36hcdbd4b5_0
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - yaml=0.1.7=hc54c509_2
  - zeromq=4.2.5=he025d50_1
  - zlib=1.2.11=h8395fce_2
  - zope=1.0=py36_1
  - zope.interface=4.5.0=py36hfa6e2cd_0
  - pip:
    - pip==19.0.2
prefix: C:\Users\micha\Anaconda3_64\envs\sports_predict_env
